# -*- coding: utf-8 -*-
"""week8day3dailychallenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wIjWm2skclXj-G9enQlIahrPux32EcsO
"""

!pip install kaggle
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

# Then move kaggle.json into the folder where the API expects to find it.
!mkdir -p ~/.kaggle/ && mv kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d saurabhbadole/latest-data-science-job-salaries-2024
!unzip latest-data-science-job-salaries-2024.zip

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('DataScience_salaries_2024.csv')
print(df.head())

df.info()
df.isnull().sum()
duplicated = df.duplicated(keep='first')
print(duplicated[duplicated == True])
df.drop_duplicates(inplace=True)
df.isnull().sum()

grouped = df.groupby('experience_level')

result = grouped['salary_in_usd'].agg(['mean', 'median'])

print(result)

mean_salary = df.groupby('experience_level')['salary_in_usd'].mean()

plt.bar(mean_salary.index, mean_salary.values)
plt.xlabel('Experience Level')
plt.ylabel('Mean Salary (USD)')
plt.title('Mean Salary by Experience Level')
plt.show()