# -*- coding: utf-8 -*-
"""Week9day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14OrhNNdoxGBzfks1LVfReajKN7Xalbq4
"""

!pip install kaggle
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

# Then move kaggle.json into the folder where the API expects to find it.
!mkdir -p ~/.kaggle/ && mv kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d shariful07/student-mental-health
!unzip student-mental-health.zip

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('Student Mental health.csv')
print(df.head())

sns.histplot(df['What is your CGPA?'])

sns.countplot(data=df, x='Choose your gender', hue='Do you have Anxiety?')

plt.title('Count of Anxiety Responses by Gender')
plt.xlabel('Gender')
plt.ylabel('Number of Responses')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

df['panic_binary'] = df['Do you have Panic attack?']
df['panic_binary'] = df['panic_binary'].replace({'Yes': 1, 'No': 0})
print(df['panic_binary'].head())
sns.scatterplot(data=df, x='Age', y='panic_binary').set(title='Panic Attacks by Age')
#Exercise 3 : Scatterplot is not the right way to represent this information because it has many dots over the same point and the age data is not perfectly continouous. There is no amount of "customizing the plot to improve its readability". Below is a plot that actually makes sense for this information
sns.histplot(data=df, x='Age', hue='panic_binary').set(title='Panic Attacks by Age')

df['anxiety_binary'] = df['Do you have Anxiety?']
df['anxiety_binary'] = df['anxiety_binary'].replace({'Yes': 1, 'No': 0})

df['depression_binary'] = df['Do you have Depression?']
df['depression_binary'] = df['depression_binary'].replace({'Yes': 1, 'No': 0})

subset = df[['Age', 'panic_binary', 'anxiety_binary', 'depression_binary']]
sns.pairplot(subset)

sns.heatmap(subset.corr(), annot=True)

g = sns.FacetGrid(df, col='What is your CGPA?', row='depression_binary')
g.map(sns.histplot, x='What is your CGPA?', y='depression_binary', data = df)